services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: iris-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/workspaces/backend:cached
    networks:
      - iris-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy  # PostgreSQLが接続可能になるまで待つ
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: iris-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/workspaces/frontend:cached
      - /workspaces/frontend/node_modules
    networks:
      - iris-network
    env_file:
      - .env
    depends_on:
      - backend
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iris-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  iris-network:
    driver: bridge
volumes:
  postgres_data:
