## ビルダーイメージの指定
FROM python:3.12-slim AS builder

RUN apt-get update && apt-get install -y \
	build-essential \
	&& rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -U pip

WORKDIR /build
COPY /app/requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

## ベースイメージの指定
FROM python:3.12-slim
ARG USERNAME=appuser
RUN useradd -ms /bin/bash $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/$USERNAME/app
COPY --from=builder /install /usr/local
COPY --chown=$USERNAME:$USERNAME app/ .

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8080
USER $USERNAME

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD pytohn -c "import urllib.request; urllib.request.get('http://localhost:8080/health', timeout=5)"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
